services:
  - type: web
    name: trackibjjf
    env: python
    buildCommand: chmod +x build.sh start.sh && ./build.sh
    startCommand: ./start.sh
    disk:
      name: ibjjf-data
      mountPath: /opt/render/project/src/instance
      sizeGB: 1
